#!/bin/bash

set -e

blue='\033[1;34m'
nocolor='\033[0m'

cd $(dirname "${0}")

for testfile in $(ls *_test.js); do
    printf "${blue}→${nocolor} Test $testfile\n"
    ../node_modules/.bin/babel-node --presets es2015 "$testfile"
done

for testfile in $(find * -name '*.tst' ! -name '*VME.tst'); do
    printf "${blue}→${nocolor} Test $testfile\n"

    testfilebase="${testfile%.*}"
    vmfile="$testfilebase".vm

    ../node_modules/.bin/babel-node --presets es2015 vm-cli.js "$vmfile"

    CPUEmulator.sh "$testfile"
done
