#!/bin/bash

set -e

blue='\033[1;34m'
nocolor='\033[0m'

cd $(dirname "${0}")

vmemulator=$(which VMEmulator.sh)
toolsdir=${vmemulator%/*}
osdir="$toolsdir"/os

for jackfile in $(ls *.jack); do
    jackfilebase="${jackfile%.*}"

    printf "${blue}→${nocolor} Test $jackfilebase\n"

    testdir="$jackfilebase"Test
    testfile="$testdir"/"$jackfilebase"Test.tst

    cp "$osdir"/*.vm "$testdir"
    cp "$jackfile" "$testdir"

    JackCompiler.sh "$testdir"

    if [ -f "$testfile" ]; then
        VMEmulator.sh "$testfile"
    else
        printf "This class requires manual testing. "
        printf "Open and run $testdir in VMEmulator and compare with the expected output.\n"
    fi
done
