#!/bin/bash

command -v fswatch >/dev/null 2>&1 || {
    printf "The program `fswatch` is required: https://github.com/emcrisostomo/fswatch\n"
    exit 1
}

cd $(dirname "${0}")

testfile="$1"
printf "Test $testfile and watch for *.hdl file changes\n"

function test {
    HardwareSimulator.sh "$testfile"
}

test
fswatch -e ".*" -i "\\.hdl$" . | (while read; do test; done)
