#!/bin/bash

set -e

blue='\033[1;34m'
nocolor='\033[0m'

cd $(dirname "${0}")

# for testfile in $(ls *_test.js); do
#     printf "${blue}→${nocolor} Test $testfile\n"
#     ../node_modules/.bin/babel-node --presets es2015 "$testfile"
# done

for jackfile in $(find * -name '*.jack'); do

    if [ "$jackfile" != "Average/Main.jack" ]; then
        continue
    fi

    printf "${blue}→${nocolor} Test $jackfile\n"

    jackfilebase="${jackfile##*/}"
    jackfilename="${jackfilebase%.*}"
    jackfiledir="${jackfile%/*}"

    builtindir="$jackfiledir"/builtin
    mkdir -p "$builtindir"
    tmpbuiltinvmfile="$jackfiledir"/"$jackfilename".vm
    builtinvmfile="$builtindir"/"$jackfilename".vm

    diydir="$jackfiledir"/diy
    mkdir -p "$diydir"
    diyvmfile="$diydir"/"$jackfilename".vm

    JackCompiler.sh "$jackfile"
    mv "$tmpbuiltinvmfile" "$builtinvmfile"

    ../node_modules/.bin/babel-node --presets es2015 compiler-cli.js "$jackfile" "$diyvmfile"

    diff --unchanged-line-format="" --old-line-format="builtin line %dn: %L" \
        --new-line-format="    diy line %dn: %L" "$builtinvmfile" "$diyvmfile"

    printf "Files match.\n"
done
