#!/bin/bash

set -e

blue='\033[1;34m'
nocolor='\033[0m'

cd $(dirname "${0}")

for testfile in $(ls *_test.js); do
    printf "${blue}→${nocolor} Test $testfile\n"
    ../node_modules/.bin/babel-node --presets es2015 "$testfile"
done

for testdir in $(ls -d */); do
    testdir=${testdir%%/}

    printf "${blue}→${nocolor} Test $testdir\n"

    builtindir="$testdir"/builtin
    mkdir -p "$builtindir"
    cp "$testdir"/*.jack "$builtindir"/
    JackCompiler.sh "$builtindir"
    rm "$builtindir"/*.jack

    diydir="$testdir"/diy
    mkdir -p "$diydir"

    for jackfile in $(find "$testdir" -name '*.jack'); do
        jackfilebase="${jackfile##*/}"
        jackfilename="${jackfilebase%.*}"

        diyvmfile="$diydir"/"$jackfilename".vm

        ../node_modules/.bin/babel-node --presets es2015 compiler-cli.js "$jackfile" "$diyvmfile"
    done

    printf "Manual testing steps:\n"
    printf "1. Read the book and/or open $builtindir in VMEmulator and observe the program behavior.\n"
    printf "2. Open $diydir in VMEmulator and verify that it behaves as expected.\n"
done
