#!/bin/bash

set -e

blue='\033[1;34m'
nocolor='\033[0m'

cd $(dirname "${0}")

for testfile in $(ls *.tst); do
    printf "${blue}→${nocolor} Test $testfile\n"

    if [ $testfile = "Memory.tst" ]; then
        printf "Skip - Requires GUI\n"
        continue
    fi

    HardwareSimulator.sh "$testfile"
done
